services:

  web:
    build: .
    entrypoint: sh -c "uv sync --group dev --group test; DEBUG=1 exec ./manage.py runserver 0.0.0.0:8000"
    container_name: django_web
    environment:
      - SECRET_KEY=${SECRET_KEY-aaa}
      - DATABASE_URL=${DATABASE_URL-postgis://postgres:postgres@postgres/postgres}
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
      - NTA_API_KEY=d8dee58f545e4a5a94687b6b3314edb9
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PYTHONWARNINGS=all
      - NEW_VEHICLE_WEBHOOK_URL=https://discord.com/api/webhooks/1364510430457757696/9jYH5R4L-WieRLYYt8wOl8pmGSGdwy29_nKi1Zd-azdJKmi5y9aDqm8P1P2dy-h9WRgh
      - TURNSTILE_SITEKEY=0x4AAAAAABhoa5RwbavjMxaF
      - TURNSTILE_SECRET=0x4AAAAAABhoa4dJtwtvOs11OVkVvsscf3M
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "35729:35729"
    restart: on-failure

  postgres:
    image: postgis/postgis
    tmpfs:
      - "/var/lib/postgresql/data/"
    # # sloppy non-durable settings, which allegedly make the tests run faster
    # # not to be used in production!
    # command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
