# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0017_locality_name_trgm'),
        ('bustimes', '0020_stoptime_trip_id_n_distinct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.timetabledatasource'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.servicecolour'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.operatorgroup'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.region'),
        ),
        migrations.AlterField(
            model_name='operatorcode',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='operatorcode',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
    ]
