# The tables already exist, as implicit many-to-many tables; all that's new is
# the explicit through models describing them.  See buses/migration_utils.py.

import django.db.models.deletion
from django.db import migrations, models

from buses.migration_utils import cascade


class Migration(migrations.Migration):
    dependencies = [
        ("busstops", "0018_alter_datasource_options_alter_region_options_and_more"),
        ("vosa", "0003_alter_registration_latest_variation_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="OperatorLicence",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "licence",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorlicence+",
                                to="vosa.licence",
                            ),
                        ),
                        (
                            "operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorlicence+",
                                to="busstops.operator",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_operator_licences",
                        "unique_together": {("operator", "licence")},
                    },
                ),
                migrations.AlterField(
                    model_name="operator",
                    name="licences",
                    field=models.ManyToManyField(
                        blank=True,
                        through="busstops.OperatorLicence",
                        to="vosa.licence",
                    ),
                ),
                migrations.CreateModel(
                    name="OperatorPaymentMethod",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorpaymentmethod+",
                                to="busstops.operator",
                            ),
                        ),
                        (
                            "paymentmethod",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorpaymentmethod+",
                                to="busstops.paymentmethod",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_operator_payment_methods",
                        "unique_together": {("operator", "paymentmethod")},
                    },
                ),
                migrations.AlterField(
                    model_name="operator",
                    name="payment_methods",
                    field=models.ManyToManyField(
                        blank=True,
                        through="busstops.OperatorPaymentMethod",
                        to="busstops.paymentmethod",
                    ),
                ),
                migrations.CreateModel(
                    name="OperatorRegion",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorregion+",
                                to="busstops.operator",
                            ),
                        ),
                        (
                            "region",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="operatorregion+",
                                to="busstops.region",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_operator_regions",
                        "unique_together": {("operator", "region")},
                    },
                ),
                migrations.AlterField(
                    model_name="operator",
                    name="regions",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="operators",
                        through="busstops.OperatorRegion",
                        to="busstops.region",
                    ),
                ),
                migrations.CreateModel(
                    name="OperatorSibling",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "from_operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="from_operatorsibling+",
                                to="busstops.operator",
                            ),
                        ),
                        (
                            "to_operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="to_operatorsibling+",
                                to="busstops.operator",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_operator_siblings",
                        "unique_together": {("from_operator", "to_operator")},
                    },
                ),
                migrations.AlterField(
                    model_name="operator",
                    name="siblings",
                    field=models.ManyToManyField(
                        blank=True,
                        through="busstops.OperatorSibling",
                        through_fields=("from_operator", "to_operator"),
                        to="busstops.operator",
                    ),
                ),
                migrations.CreateModel(
                    name="ServiceOperator",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="serviceoperator+",
                                to="busstops.operator",
                            ),
                        ),
                        (
                            "service",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="serviceoperator+",
                                to="busstops.service",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_service_operator",
                        "unique_together": {("service", "operator")},
                    },
                ),
                migrations.AlterField(
                    model_name="service",
                    name="operator",
                    field=models.ManyToManyField(
                        blank=True,
                        through="busstops.ServiceOperator",
                        to="busstops.operator",
                    ),
                ),
                migrations.CreateModel(
                    name="SIRISourceOperator",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "operator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="sirisourceoperator+",
                                to="busstops.operator",
                            ),
                        ),
                        (
                            "sirisource",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DB_CASCADE,
                                related_name="sirisourceoperator+",
                                to="busstops.sirisource",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "busstops_sirisource_operators",
                        "unique_together": {("sirisource", "operator")},
                    },
                ),
                migrations.AlterField(
                    model_name="sirisource",
                    name="operators",
                    field=models.ManyToManyField(
                        blank=True,
                        through="busstops.SIRISourceOperator",
                        to="busstops.operator",
                    ),
                ),
            ],
            database_operations=cascade(
                (
                    "busstops_operator_licences",
                    "operator_id",
                    "busstops_operator",
                    "noc",
                ),
                ("busstops_operator_licences", "licence_id", "vosa_licence", "id"),
                (
                    "busstops_operator_payment_methods",
                    "operator_id",
                    "busstops_operator",
                    "noc",
                ),
                (
                    "busstops_operator_payment_methods",
                    "paymentmethod_id",
                    "busstops_paymentmethod",
                    "id",
                ),
                (
                    "busstops_operator_regions",
                    "operator_id",
                    "busstops_operator",
                    "noc",
                ),
                ("busstops_operator_regions", "region_id", "busstops_region", "id"),
                (
                    "busstops_operator_siblings",
                    "from_operator_id",
                    "busstops_operator",
                    "noc",
                ),
                (
                    "busstops_operator_siblings",
                    "to_operator_id",
                    "busstops_operator",
                    "noc",
                ),
                ("busstops_service_operator", "service_id", "busstops_service", "id"),
                (
                    "busstops_service_operator",
                    "operator_id",
                    "busstops_operator",
                    "noc",
                ),
                (
                    "busstops_sirisource_operators",
                    "sirisource_id",
                    "busstops_sirisource",
                    "id",
                ),
                (
                    "busstops_sirisource_operators",
                    "operator_id",
                    "busstops_operator",
                    "noc",
                ),
            ),
        ),
    ]
