# Generated by Django 6.1.1 on 2026-09-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busstops", "0019_m2m_through_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("description", "Description"),
                            ("line_brand", "Marketing name"),
                        ],
                        default="description",
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busstops.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "field")},
            },
        ),
    ]
