# Generated by Django 6.1.1 on 2026-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0018_merge'),
        ('busstops', '0020_serviceoverride'),
    ]

    operations = [
    ]
