# Generated by Django 6.1.1 on 2026-09-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0021_merge_0018_merge_0020_serviceoverride'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='idx_service_current',
        ),
        migrations.RemoveIndex(
            model_name='stopusage',
            name='idx_stopusage_stop_id',
        ),
        migrations.RemoveIndex(
            model_name='stopusage',
            name='idx_stopusage_service_id',
        ),
    ]
