# Generated by Django 6.0.6 on 2026-07-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_locality_name_trgm'),
        ('disruptions', '0001_squashed_0007_alter_situation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectedjourney',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='severity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(default=236, limit_choices_to={'name__in': ('bustimes.org', 'TfL', 'TfL disruptions', 'TfL statuses', 'BODS disruptions', 'BODS cancellations', 'Bus Open Data', 'Translink')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
