# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0018_alter_datasource_options_alter_region_options_and_more'),
        ('bustimes', '0021_alter_bankholidaydate_bank_holiday_and_more'),
        ('disruptions', '0008_affectedjourney_date_situation_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedjourney',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='disruptions.situation'),
        ),
        migrations.AlterField(
            model_name='affectedjourney',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.trip'),
        ),
        migrations.AlterField(
            model_name='call',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='disruptions.affectedjourney'),
        ),
        migrations.AlterField(
            model_name='call',
            name='stop_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.stoptime'),
        ),
        migrations.AlterField(
            model_name='consequence',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='disruptions.situation'),
        ),
        migrations.AlterField(
            model_name='link',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='disruptions.situation'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(default=236, limit_choices_to={'name__in': ('bustimes.org', 'TfL', 'TfL disruptions', 'TfL statuses', 'BODS disruptions', 'BODS cancellations', 'Bus Open Data', 'Translink')}, on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
        migrations.AlterField(
            model_name='validityperiod',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='disruptions.situation'),
        ),
    ]
