# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busstops", "0014_service_create_route_links"),
        ("disruptions", "0009_alter_situation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="situation",
            name="source",
            field=models.ForeignKey(
                default=236,
                limit_choices_to={
                    "name__in": (
                        "bustimes.org",
                        "TfL",
                        "TfL disruptions",
                        "TfL statuses",
                        "BODS disruptions",
                        "BODS cancellations",
                        "Bus Open Data",
                        "Translink",
                        "Nottingham City Transport",
                        "Intalink",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="busstops.datasource",
            ),
        ),
    ]
