# Generated by Django 6.1.1 on 2026-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0011_m2m_through_models'),
        ('disruptions', '0012_alter_situation_source'),
    ]

    operations = [
    ]
