# Generated by Django 6.1.1 on 2026-09-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0022_remove_service_idx_service_current_and_more'),
        ('disruptions', '0013_merge_20260922_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(default=236, limit_choices_to={'name__in': ('bustimes.org', 'TfL', 'TfL disruptions', 'TfL statuses', 'BODS disruptions', 'BODS cancellations', 'Bus Open Data', 'Translink', 'Nottingham City Transport', 'Intalink', "McGill's", 'Arriva UK')}, on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
    ]
