# Generated by Django 6.1.1 on 2026-09-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0003_m2m_through_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('order',)},
        ),
    ]
