# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0003_invitation'),
        ('busstops', '0017_locality_name_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoruser',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='operatoruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
