# Generated by Django 6.0.7 on 2026-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0016_alter_route_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='timing_point',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
