# Generated by Django 6.0.6 on 2026-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0016_alter_route_line_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankholidaydate',
            index=models.Index(fields=['bank_holiday'], name='bustimes_ba_bank_ho_121b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankholidaydate',
            index=models.Index(fields=['date'], name='bustimes_ba_date_b1c2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarbankholiday',
            index=models.Index(fields=['calendar'], name='bustimes_ca_calenda_b21e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarbankholiday',
            index=models.Index(fields=['bank_holiday'], name='bustimes_ca_bank_ho_c0f9fb_idx'),
        ),
    ]
