# Generated by Django 6.0.7 on 2026-07-18 00:59

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('bustimes', '0017_stoptime_timing_point'),
    ]

    operations = [
        migrations.RunSQL("SET lock_timeout = '2s'", reverse_sql=migrations.RunSQL.noop),
        migrations.RemoveField(
            model_name='stoptime',
            name='timing_status',
        ),
    ]
