# Generated by Django 6.0.7 on 2026-07-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('bustimes', '0018_remove_stoptime_timing_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stoptime',
                    name='trip',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bustimes.trip'),
                ),
            ],
            database_operations=[
                migrations.RunSQL("SET lock_timeout = '2s'", reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS "bustimes_stoptime_trip_id_0be81724";',
                    reverse_sql='CREATE INDEX CONCURRENTLY "bustimes_stoptime_trip_id_0be81724" ON "bustimes_stoptime" ("trip_id");',
                ),
            ],
        ),
    ]
