# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0018_alter_datasource_options_alter_region_options_and_more'),
        ('bustimes', '0020_stoptime_trip_id_n_distinct'),
        ('vosa', '0003_alter_registration_latest_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankholidaydate',
            name='bank_holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.bankholiday'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
        migrations.AlterField(
            model_name='calendarbankholiday',
            name='bank_holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.bankholiday'),
        ),
        migrations.AlterField(
            model_name='calendarbankholiday',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.calendar'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.calendar'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='route',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='vosa.registration'),
        ),
        migrations.AlterField(
            model_name='route',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='busstops.service'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
        migrations.AlterField(
            model_name='route',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.version'),
        ),
        migrations.AlterField(
            model_name='timetabledatasource',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.region'),
        ),
        migrations.AlterField(
            model_name='version',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.timetabledatasource'),
        ),
    ]
