# Generated by Django 6.1 on 2026-08-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0018_alter_datasource_options_alter_region_options_and_more'),
        ('bustimes', '0023_note_m2m_on_delete_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptime',
            name='stop_code',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stoptime',
                    name='stop',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='busstops.stoppoint',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE bustimes_stoptime ADD CONSTRAINT stoptime_stop_id_not_null "
                    "CHECK (stop_id IS NOT NULL) NOT VALID",
                    reverse_sql="ALTER TABLE bustimes_stoptime DROP CONSTRAINT stoptime_stop_id_not_null",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE bustimes_stoptime VALIDATE CONSTRAINT stoptime_stop_id_not_null",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE bustimes_stoptime ALTER COLUMN stop_id SET NOT NULL",
                    reverse_sql="ALTER TABLE bustimes_stoptime ALTER COLUMN stop_id DROP NOT NULL",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE bustimes_stoptime DROP CONSTRAINT stoptime_stop_id_not_null",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
