# Generated by Django 6.1.1 on 2026-09-14 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0020_serviceoverride'),
        ('bustimes', '0025_m2m_through_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField()),
                ('category', models.CharField()),
                ('comment', models.CharField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='bustimes.importtask')),
            ],
        ),
        migrations.CreateModel(
            name='DodgyRouteLink',
            fields=[
                ('dataqualityobservation_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, parent_link=True, primary_key=True, serialize=False, to='bustimes.dataqualityobservation')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodgy_link_from', to='busstops.stoppoint')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodgy_link_to', to='busstops.stoppoint')),
            ],
            bases=('bustimes.dataqualityobservation',),
        ),
        migrations.CreateModel(
            name='DodgyRunTime',
            fields=[
                ('dataqualityobservation_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, parent_link=True, primary_key=True, serialize=False, to='bustimes.dataqualityobservation')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodgy_time_from', to='busstops.stoppoint')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dodgy_time_to', to='busstops.stoppoint')),
            ],
            bases=('bustimes.dataqualityobservation',),
        ),
    ]
