# Generated by Django 6.1.1 on 2026-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0017_add_calendar_indexes'),
        ('bustimes', '0026_importtask_dataqualityobservation_dodgyroutelink_and_more'),
    ]

    operations = [
    ]
