# Generated by Django 6.1.1 on 2026-09-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0027_merge_20260922_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendardate',
            options={'ordering': ('start_date',)},
        ),
        migrations.RemoveIndex(
            model_name='bankholidaydate',
            name='bustimes_ba_bank_ho_121b7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankholidaydate',
            name='bustimes_ba_date_b1c2bb_idx',
        ),
    ]
