# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('vosa', '0002_alter_licence_authorised_discs_alter_licence_discs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='latest_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='latest', to='vosa.variation'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vosa.licence'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vosa.registration'),
        ),
    ]
