# Generated by Django 6.0.6 on 2026-07-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_locality_name_trgm'),
        ('vehicles', '0022_alter_vehicle_fleet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirisubscription',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
