# Generated by Django 6.0.7 on 2026-07-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_locality_name_trgm'),
        ('vehicles', '0023_sirisubscription_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirisubscription',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
