# Generated by Django 6.1 on 2026-08-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0018_alter_datasource_options_alter_region_options_and_more'),
        ('bustimes', '0021_alter_bankholidaydate_bank_holiday_and_more'),
        ('vehicles', '0024_alter_sirisubscription_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirisubscription',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='busstops.datasource'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='bustimes.garage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_journey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='latest_vehicle', to='vehicles.vehiclejourney'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='busstops.datasource'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclecode',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_from', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_from', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_from', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_to', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_to', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, related_name='revision_to', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclerevisionfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vehicles.vehiclefeature'),
        ),
        migrations.AlterField(
            model_name='vehiclerevisionfeature',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='vehicles.vehiclerevision'),
        ),
    ]
